---

branch-protection-check-name: Changelog entry
action-hints:
  check-title-prefix: "Chronographer: "
  external-docs-url: >-
    https://github.com/jacksonsr451/test-runner/tree/main/doc/en/contributing.html#preparing-pull-requests
  inline-markdown: >-
    See
    https://github.com/jacksonsr451/test-runner/tree/main/doc/en/contributing.html#preparing-pull-requests
    for details.
enforce-name:
  suffix: .rst
exclude:
  humans:
  - pyup-bot
labels:
  skip-changelog: skip news

...
